[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Sparrow"
requires-python = ">= 3.8"
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}

